#! /bin/sh
#all programs exe
pgrep -x sxhkd > /dev/null || sxhkd &
picom --backend glx --experimental-backends --blur-method dual_kawase & 
devilspie &
#sh /home/root99/.config/i3/wallpaper.sh &
#bgchd -dir /home/root99/Downloads/Wall -bcknd feh -intv 30s -rpl &
feh -z --bg-scale --no-fehbg /home/root99/Downloads/Wall/sung.jpg
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
sh /home/root99/.config/polybar/launch.sh &
xss-lock --transfer-sleep-lock -- i3lock-fancy -g & 
xautolock -time 60  -locker "systemctl suspend" -detectsleep &
nm-applet &
dunst &
xfce4-power-manger &
greenclip daemon &
#btops &
bspc monitor -d ' 1.  '  ' 2.  '  ' 3.  '  ' 4.  '  ' 5.  '  ' 6. '  ' 7.  '  ' 8.  '  ' 9.  '
#bspc monitor -d "1" "2" "3" "4" "5" "6" "7" "8" "9"
bspc config border_width         1
bspc config window_gap           0
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#EA0808"
bspc config presel_feedback_color	      "#5e81ac"
#bspc config top_padding 25
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^2'
bspc rule -a Brave-browser-nightly desktop='^2'
bspc rule -a Org.gnome.Nautilus desktop='^3'
bspc rule -a Pcmanfm desktop='^3'
bspc rule -a Code desktop='^4'
#bspc rule -a Spotify desktop='^6'
bspc rule -a gimp desktop='^8'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#bspc rule -a Alacritty state=fullscreen
